# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015

# -------------------- 共通設定 --------------------

# メッセージの言語
lang: ja

# 自分自身に送信可能とするかどうか。
enableSendSelf: false

# UIを表示する系統のコマンドを実行したときに、
# UIの前に挿入する空行の行数を設定します。
# 0から9まで指定可能です。
uiEmptyLines: 2

# プレイヤー名簿を利用するかどうか。
# プレイヤー名簿では、サーバーに１度でも接続したことがあるプレイヤー全てが
# 一覧にリストアップされます。
enablePlayerList: false

# 指定できる宛先の最大数
maxDestination: 10

# 指定できる宛先グループの最大数
maxDestinationGroup: 3

# メールの保存期間（日数）
# 例えば30を指定した場合、送信してから31日経ったメールは自動的に削除されます。
mailStorageTermDays: 30

# メールスパム保護期間（秒）
# 例えば15を指定した場合、メールを送信してから次のメールを送信できるまで、
# 15秒の経過が必要になります。
mailSpamProtectionSeconds: 15

# プレイヤーがログインした時に、未読一覧を表示するまでの時間（秒）。
loginNotificationDelaySeconds: 3

# -------------------- アイテム添付設定 --------------------

# メールにアイテムの添付を可能にするかどうか。
enableAttachment: true

# メールの添付ボックスのサイズを指定します。
# 1列（＝9個）から6列（＝54個）まで指定可能です。
attachBoxSize: 1

# 同時に使用可能な添付ボックスの個数を指定します。
maxAttachmentBoxCount: 3

# メールの添付ボックスを操作不可に設定したいワールドを指定します。
# 例えば disableWorldsToOpenAttachment: ['sozai']  と設定すると、
# sozaiというワールド名に居るプレイヤーは、送信メールの添付ボックスや
# 受信したメールの添付ボックスを開くことができなくなります。
disableWorldsToOpenAttachBox: []

# -------------------- 着払い設定 --------------------

# 経済プラグインの通貨を利用して、着払い料金を設定可能とするかどうか。
# この機能を利用するには、Vaultと、経済プラグインを、一緒に導入する必要があります。
enableCODMoney: true

# 着払い料金として、アイテムをリクエストできるようにするかどうか。
enableCODItem: true

# 着払い料金を相手に支払う場合、入金後の金額が一致しない場合に、エラーとするかどうか。
# Essentialsのmax-moneyなどで、お金の上限を設定している場合は、
# 入金で上限を超えると送金した金額が消滅するので、この項目をtrueに設定してください。
# 入金時に税金を取るような経済プラグインを利用している場合は、
# 送金ができなくなりますので、この項目をfalseにしてください。
depositErrorOnUnmatch: true

# -------------------- 送信料金設定 --------------------

# メールを作成したりアイテムを添付したりするために料金を必要とするかどうか。
# 経済プラグインとVaultが導入されている必要があります。
enableSendFee: false

# 1つの宛先にメールを作成する料金です。
# 送信先が複数ある場合は、送信先の数だけ倍になります。
sendFee: 10

# メールにアイテムを1個添付する料金です。
attachFee: 10

# 着払い料金に対する着払い税です。パーセンテージで指定してください。
# 例えば、codMoneyTax: 10 とすると、着払い料金 $300 を指定したメールは、
# 着払い料金の 10% の $30 が、追加で必要になります。
codMoneyTax: 0

# 着払いアイテムに対する着払い税です。要求アイテム1個に対する金額で指定してください。
# 例えば、codItemTax: 10 とすると、ダイアモンド8個を着払いアイテムとして指定すると、
# $80 (=$10 * 8) の税金が、追加で必要になります。
codItemTax: 0

# -------------------- メールグループ設定 --------------------

# 1プレイヤーが作成可能なグループの最大数。
# OPや、'undine.group.infinite-create'パーミッションを持った人は、
# この数値に関係なく無限に作成可能です。
maxCreateGroup: 5

# 1グループに追加できる最大プレイヤー数
# OPや、'undine.group.infinite-add-member'パーミッションを持った人は、
# この数値に関係なく無限に追加可能です。
maxGroupMember: 15

# グループへのメール送信権限のデフォルト
# OP → OPのみがグループへメール送信可能
# OWNER → オーナーとOPがグループへメール送信可能
# MEMBER → メンバーならグループへメール送信可能
# EVERYONE → 誰でもグループへメール送信可能
sendModeDefault: MEMBER

# グループのメンバー変更権限のデフォルト
# OP → OPのみが変更可能
# OWNER → オーナーとOPが変更可能
# MEMBER → メンバーなら変更可能
# EVERYONE → 誰でも変更可能
modifyModeDefault: OWNER

# グループの解散権限のデフォルト
# OP → OPのみが解散可能
# OWNER → オーナーとOPが解散可能
# MEMBER → メンバーなら解散可能
# EVERYONE → 誰でも解散可能
dissolutionModeDefault: OWNER

# 特殊グループ All (全プレイヤーへのメールが送信できるグループ) への
# 送信権限を指定します。
specialGroupAllSendMode: OP

# 特殊グループ PEX (PermissionsExのグループ) への送信権限のデフォルトを指定します。
# PermissionsExのグループのoption設定に、"send-mode" を設定することで、
# グループごとに細かくSendModeを指定することが可能です。詳しくはフォーラムを参照してください。
specialGroupPexSendMode: OP

